name: Build and Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'setup.py'
      - 'pyproject.toml'
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build setuptools wheel

      - name: Install project and test requirements
        run: |
          pip install .
          pip install -r requirements.txt pytest

      - name: Run tests
        run: pytest

      - name: Build package
        run: python -m build --sdist --wheel

      - name: Publish to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          python -m twine upload dist/*
